Add sidebar menu with larivaar assist option
KhalisFoundation/learn-larivaar pull request #30
Opened 2023-06-15 05:39 UTC by Gauravjeetsingh

https://github.com/KhalisFoundation/learn-larivaar/assets/1990932/88c91d96-995d-4dc5-986c-a3b228735b8f

2023-06-20 09:32 UTC, theamanjs requested changes

2023-06-20 09:32 UTC, theamanjs commented on App.tsx
> +          // eslint-disable-next-line react/no-unstable-nested-components
Should change the code according to this https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md

2023-06-20 09:32 UTC, theamanjs commented on components/Launchpad/lauchpad.tsx
> +      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
the condition is logically opposite

2023-07-06 06:20 UTC, Gauravjeetsingh commented on App.tsx
> +          // eslint-disable-next-line react/no-unstable-nested-components
@theamanjs veerji, this is fixed in pull request #32

2023-07-06 06:22 UTC, Gauravjeetsingh commented on components/Launchpad/lauchpad.tsx
> +      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
It appears that way, but the light-content means white text in status bar, and the dark-content means black colored text in status bar. 

So in dark mode, we need light content (white colored text) in status bar else we need dark content (black colored text)

2023-08-09 05:50 UTC, theamanjs commented on components/Launchpad/lauchpad.tsx
> +      <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
Umm okay

2023-08-09 06:06 UTC, theamanjs approved these changes

2023-08-09 06:07 UTC, merged